name: CI Delivery Management

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_USER: test
      DB_PASSWORD: test
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: testdb
      DATABASE_URL: "postgresql+asyncpg://test:test@db:5432/testdb"
      RABBITMQ_USER: test
      RABBITMQ_PASSWORD: test
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_VHOST: /
      RABBITMQ_URL: amqp://test:test@rabbitmq:5672/
      LOG_LEVEL: INFO
      ENABLE_STRUCTURED_LOGS: true
    steps:
      - name: Checkout código
        uses: actions/checkout@v3


      - name: Rodar testes no container tests
        run: |
          docker compose -f docker-compose-test.yml up --build --exit-code-from tests tests

      - name: Copiar relatório de coverage
        run: |
          docker cp $(docker ps -a --filter "name=tests" --format "{{.ID}}" | head -n1):/app/coverage.xml ./coverage.xml

      - name: Publicar relatório de cobertura
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
